### ISSUE TITLE
Doesn't Seem to Work With 1.21.9

### ISSUE THREAD

**Issue by BineGrid** [nulli0n/ExcellentEnchants-spigot#196]
Currently getting this error when my 1.21.9 paper server starts up. 
`10/7 2:22:47 PM [Error] [BootstrapProviderStorage] Failed to run bootstrapper for plugins/ExcellentEnchants-5.2.1.jar. This plugin will not be loaded.Copy
10/7 2:22:47 PM [Error] java.lang.NoSuchMethodError: 'io.papermc.paper.plugin.lifecycle.event.types.LifecycleEventType$Prioritizable io.papermc.paper.registry.event.RegistryEventProvider.freeze()'Copy
10/7 2:22:47 PM [Error] at ExcellentEnchants-5.2.1.jar/su.nightexpress.excellentenchants.EnchantsBootstrap.bootstrap(EnchantsBootstrap.java:83) ~[ExcellentEnchants-5.2.1.jar:?]Copy`

**Comment by nulli0n** [comment]
v5.3.0 supports 1.21.10
